#167014104 Deploy app to heroku
andela/ah-frontend-space pull request #12
Opened 2019-07-05 11:48 UTC by sebbss

#### What does this PR do?

Deploy the app to Heroku.

#### Description of Task to be completed?

- add static.json
- modify scripts for running the application
#### How should this be manually tested?
to view the Heroku deployment you can visit the heroku app through this [link](https://ah-frontend-space.herokuapp.com/)

#### What are the relevant pivotal tracker stories?

[#167014104](https://www.pivotaltracker.com/story/show/167014104)

#### Screenshots (if appropriate)

![image](https://user-images.githubusercontent.com/44563961/60720580-e2479000-9f33-11e9-9926-3ddef4031bf1.png)

2019-07-05 12:25 UTC, frankopkusianwar approved these changes
LGTM

2019-07-08 10:11 UTC, NicholusMuwonge requested changes
Please kindly add an empty line at the end of this file

2019-07-08 10:15 UTC, richien requested changes

2019-07-08 10:15 UTC, richien commented on app.json
> +
@sebbss , kindly add a new line to this file as well as to the `statis.json` file. Other than that, I have tested the deployed app and it works as described in the PR.

2019-07-08 12:41 UTC, MuhanguziDavid reviewed
Nice work with the deployment @sebbss , please ensure that your commit follows the Engineering playbook standards

2019-07-08 12:56 UTC, richien approved these changes
Nice work @sebbss.

2019-07-08 12:59 UTC, NicholusMuwonge approved these changes
Thanks for the excellent work @sebbss.

2019-07-08 13:36 UTC, merged